device: cuda
result_path: results

dataset:
  name: DocRED
  kwargs:
    sets:
      train: "train_annotated.json"
      dev  : "dev.json"
      test : "test.json"
    num_class: 97
    max_seq_length: 1024

encoder:
  name: roberta-large
  lazy: True

model:
  name: atlop
