device: cuda
result_path: results/redocred

dataset:
  name: ReDocRED
  sets:
    train: "train_revised.json"
    dev  : "dev_revised.json"
    test : "test_revised.json"
  num_class: 97
  max_seq_length: 1024
  cached_location: cached.pkl

encoder:
  name: roberta-large
  lazy: True

model:
  name: atlop

trainer:
  epochs: 30
  batch_size: 4
  model_save: best.pt
  gradient_accumulation_steps: 1

optimizer:
  name: Adam
  kwargs:
    betas:
      - 0.9 # beta1
      - 0.98 # beta2
    eps: !!float 1e-9

lr_scheduler:
  name: Linear
  warmup_ratio: 0.06
